trigger:
  branches:
    include:
      - main

pool:
  name: 'RWMS Agent pool'

steps:
  

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build -- --prod
    displayName: 'Build Angular App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
